FROM rabbitmq:3.8

# RUN rabbitmq-plugins enable --offline rabbitmq_management
CMD ["rabbitmq-server"]

FROM python:3.12.0b1-alpine
WORKDIR /code
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
COPY ./listenerRabbitmq/*.py .

EXPOSE 4369 5671 5672 25672
RUN python listener.py
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8080"]