version: '3'

networks:
    my-network:
        driver: bridge

volumes:
  postgres_data:
  rabbit1:

services:
  rabbit1:
    build:
      context: .
      dockerfile: Dockerfile-rabbitmq
    image: "rabbitmq:3-management"
    hostname: rabbit1
    environment:
      RABBITMQ_ERLANG_COOKIE: "TESTVOLUME"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"
    networks:
        - my-network
    tty: true
    volumes:
      - rabbit1:/var/lib/rabbitmq
      - ./conf/:/etc/rabbitmq/
    command: bash -c "sleep 10; rabbitmq-server;"
  my-app:
    build:
       context: .
       dockerfile: Dockerfile
    container_name: my-app
    restart: always
    ports:
      - "8000:8000"
    deploy:
        resources:
            limits:
              cpus: "0.1"
              memory: 50M
    networks:
      - my-network
    depends_on:
      - postgres
  postgres:
    image: postgres:13.1
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: 250M
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-network